apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: CreateEvent_V2
  description:  |
    The CreateEvent_V2 service is part of the integration flow Customer Events Retrieval.
spec:
  type: openapi
  owner: Developer
  lifecycle: demo
  definition:
    $text: https://github.com/baludeepak7/CreateEvent_V2/blob/main/createevent_v2.yaml
    
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: CreateEvent_V2
  description: |
    The CreateEvent_V2 service is part of the integration flow Customer Events Retrieval.
  annotations:
    gitlab.com/project-id: '48576071'
    sonarqube.org/project-key: com.binpipe.spboot:demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: demo
  owner: Developer
  providesApis:
    - CreateEvent_V2
